sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t 125564648/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 125564648/react-test npm test
  
after_success:
  - docker build -t 125564648/multi-client ./client
  - docker build -t 125564648/multi-nginx ./nginx
  - docker build -t 125564648/multi-server ./server
  - docker build -t 125564648/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push 125564648/multi-client
  - docker push 125564648/multi-nginx 
  - docker push 125564648/multi-server 
  - docker push 125564648/multi-worker 